name: First Pipeline

on:
   push:
    branches: [ master ] 

jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
  - name : Checkout Code
    uses: actions/checkout@v6

  - name: check docker version
    run: docker --version

  - name: check docker compose version
    run: docker compose version

  - name: Run docker compose
    run: docker compose -f docker-compose.yaml up -d --build 
    
  - name: wait for containers to run
    run: sleep 30

  - name: Show running containers
    run: docker ps

  - name: Stop containers
    run: docker compose -f docker-compose.yaml down
  
     
      
